variables:
  FDO_UPSTREAM_REPO: mesa/demos

include:
  - project: 'freedesktop/ci-templates'
    ref: 3f37cc0e461f5b0c815409bf6f55759f26a74e9c
    file: '/templates/debian.yml'

stages:
  - container
  - build


# When & how to run the CI
.ci-run-policy:
  retry:
    max: 2
    when:
      - runner_system_failure
  # Cancel CI run if a newer commit is pushed to the same branch
  interruptible: true


# CONTAINERS

# Debian 11 based x86 build image
x86_build:
  stage: container
  extends:
    - .fdo.container-build@debian
    - .ci-run-policy
  variables:
    FDO_DISTRIBUTION_VERSION: bullseye-slim
    FDO_REPO_SUFFIX: "debian/$CI_JOB_NAME"
    # No need to pull the whole repo to build the container image
    GIT_STRATEGY: none
    # /!\ Bump the TAG when modifying the DEBS
    FDO_DISTRIBUTION_TAG: &x86_build "2022-05-16"
    FDO_DISTRIBUTION_PACKAGES: >-
      build-essential
      meson
      pkg-config
      ninja-build
      mingw-w64
      wine

      freeglut3-dev
      libdrm-dev
      libegl-dev
      libgbm-dev
      libgl-dev
      libgles-dev
      libudev-dev
      libwayland-dev
      libx11-dev
      libxcb1-dev
      wayland-protocols
      libosmesa6-dev

.use-x86_build:
  variables:
    TAG: *x86_build
  image: "$CI_REGISTRY_IMAGE/debian/x86_build:$TAG"
  needs:
    - x86_build


# BUILD

.build:
  stage: build
  extends:
    - .ci-run-policy
  variables:
    GIT_DEPTH: 10
  script:
    - meson _build
      --prefix $PWD/install
      --buildtype debug
      ${EXTRA_OPTION}
    - ninja -C _build -j4
    - ninja -C _build install

build:
  extends:
    - .use-x86_build
    - .build
  variables:
    EXTRA_OPTION: >
      -Dauto_features=enabled

build-mingw:
  extends:
    - .use-x86_build
    - .build
  before_script:
    - .gitlab-ci/prepare-glut-mingw.sh
  variables:
    EXTRA_OPTION: >
      --cross-file=.gitlab-ci/x86_64-w64-mingw32
      -Dwith-glut=/tmp/freeglut-mingw
